### ISSUE TITLE
[FR] List Pending Tasks in all Notes

### ISSUE THREAD

**Issue by shivanthzen** [renerocksai/telekasten.nvim#154]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
It is easier for me to manage my TODOs if I can  see a list of incomplete todos that you have created in your daily notes.  I use this feature in obsidian very frequently.
**Describe the solution you'd like**
I would like to see all todo in a list ( A telescope list may be ?)
**Describe alternatives you've considered**
To create a separate Note for storign todos. This will losse the context for my tasks.
**Additional context**

**Comment by lambtho12** [comment]
Allow me to rephrase in order to make sure I understand correctly:

You have different notes, each one having todo lists formatted with `- [ ] todo item`. 
You would like a function to retrieve all `- [ ] todo item`that are not marked as done `- [x] done item`.

Is that correct?

----
This is fairly easy to do with a regex. You could use `search_note` with a custom filter to output all these in a picker.
See https://github.com/renerocksai/telekasten.nvim/issues/137#issuecomment-1144986685 on how to craft such a picker.
A regex like this one should work: `^\s*- \[ \] .*$` see [here](https://regex101.com/r/iqK89K/1) for details on what that does.

**Comment by renerocksai** [comment]
100% ack. Please map a shortcut as @lambtho12 just described above.

**Comment by lambtho12** [comment]
@renerocksai , I think I will write a small section of the wiki to explain how to build custom pickers like that with these examples, so it is clearer.
