### ISSUE TITLE
Exporting to HTML

### ISSUE THREAD

**Issue by shivanthzen** [renerocksai/telekasten.nvim#157]
Are there any tools that I can try to export my markdwon notes to html ? mdzk seems like usable  but it is still in development phase. What tools do you guys use ? I'm looking for something that can create an html static site based on the current telekasten folder, with all the interlinks. Also support for some advanced markdown tools like mermaid etc.

**Comment by lambtho12** [comment]
In the past I used [neuron](https://neuron.zettel.page/) for that. This is now discontinued because the dev has made [emanote](https://emanote.srid.ca/), which looks even better and more powerful. It has extended markdown support, custom css, etc. 
I do not use such tools at the moment (I live in my terminal as much as I can) but if I were this is definitely the one I would use. I think most of telekasten possibilities would interface quite well with emanote. The only possible friction point I can think of is of (but maybe it is not even a problem) would be the support of relative links when working with sub-directories. This is something you should test.

**Comment by lambtho12** [comment]
There is also the [markdown preview plugin for (n)vim](https://github.com/iamcco/markdown-preview.nvim)

**Comment by shivanthzen** [comment]
Emanote works for me !!!!
Thanks
