### ISSUE TITLE
[BUG] goto_today doesn't use daily template

### ISSUE THREAD

**Issue by abdullatif-k** [renerocksai/telekasten.nvim#206]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
`goto_today` does not create a template if `follow_creates_nonexisting = false` because of  [this line here](https://github.com/renerocksai/telekasten.nvim/blob/cfa3c6e038ae32bf15cb549ad3a879653bef2fdb/lua/telekasten.lua#L1773)

**To Reproduce**
1. Create daily template
2. set `follow_creates_nonexisting = false`
3. Start nvim and execute `goto_today`
4. Notice the template not being used

**Expected behavior**
Should use the daily template even if `follow_creates_nonexisting` is false.

**Screenshots**

**Operating system (please complete the following information):**

**Additional context**

**Comment by lambtho12** [comment]
Actually, it there was an other issue there... Fixed in https://github.com/renerocksai/telekasten.nvim/commit/cdbb40de49c39ddc095b39542d76f491b6aa49db

Basically, I agree that `GotoToday` should always create the new note and use the template. `GotoDate` behavior however should be dependent on `dailies_create_nonexsisting` as documented already.
