### ISSUE TITLE
[FR] new_note but allow users to select directory first

### ISSUE THREAD

**Issue by Sleepful** [renerocksai/telekasten.nvim#277]
Right now you can add the subdirectory in the title of the `new_note` and it the note will land there.

This is nice. But sometimes my memory doesn't remember quite well which directories I had created previously, so it would be nice to get a command like `new_note_in_directory` that first gets a fuzzy search of available directories and then prompts for the title, creating the new note inside the selected subdirectory.

This is the kind of thing that can be written in the user config but I figured it would be nice to include it in the package.

Thoughts?

**Comment by lambtho12** [comment]
This is indeed something that has been bothering me as well. 

Instead of adding a new function though I think we could just rework the pipeline of new_note a bit, add an option so the user can tweak the default behavior and let the option be changed so custom mappings can be made to call directly the different options

With that, when you would call new_note
1. A picker would pop and ask you to select the subdir for the new note (as you propose)
2. You set the title (as currently)

The option that the user could tweak would be `new_note_dir` = `ask`, `home`, `current`. With `ask`, the user will always be asked (as proposed above), (unless there is no subdir). `home` would be similar to what we have now; the user would still be able to specify a relative path in the title name if they would like. With `current` the note would be placed in the same directory as the current opened buffer if possible, otherwise in home.

**Comment by niderhoff** [comment]
You can define folder names using path notation: `my_folder/my_note`. For me I can just start typing folder name an autocomplete popup will turn up if I hit tab.

**Comment by lambtho12** [comment]
I believe this is no kinda irrelevant with the fix in 24fd8c1, as suggested in #293. 

Feel free to reopen if I missed something.
