### ISSUE TITLE
[FR] Please add the ability to disable folding

### ISSUE THREAD

**Issue by mediapathic** [renerocksai/telekasten.nvim#291]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
Folding in telekasten is causing problems with other folding solutions, and I'd like to disable it entirely.

**Describe the solution you'd like**
Following on from #243 , but opening as a new issue because my tool sets and methods have changed quite a bit:
I'm currently having a problem wherein whenever I leave a buffer and then return to it, all indent folds (as opposed to markdown header folds) are unfolded. I've done a lot of testing of turning various plugins on and off, and sadly, I have come to the conclusion that telekasten is causing this to happen. 

So, I would like to request a setting to disable all ways in which telekasten cares about or engages with folding. I suspect I'm not alone in this- folding in vim is, ah... fraught, and I've spent many frustrating hours (not just with telekasten but many other methods) trying to get it to work the way I want. 

Now, if there's a solution for my specific problem of "don't ever unfold anything" I'd take that as well, but I suspect that just being able to disable folding entirely would be the cleanest solution for both this and other potential problems. 

My relevant config as it stands, for the record: 

```
      take_over_my_home      = true,
      auto_set_syntax        = false,
      install_syntax         = true,
      auto_set_filetype      = false,
```
but I've had the same problem setting all of these to false.

For additional context, I also use vimwiki (and it sets filetype to vimwiki.markdown), but, again, when vimiki is off and tekekasten is active, I still don't get the folding behavior I want.

Being able to have consistent persistent folding is increasingly important to my workflows (I'm working a lot with very very long markdown files), so this is kind of important for me. 

Thanks!

**Comment by renerocksai** [comment]
Folding is outside of the scope of Telekasten. It doesn't have folding features, leaves those to other plugins. Well, I just checked: in ftplugin there are functions that enable markdown folding. However, if they're not called, they don't do anything.

Telekasten is not triggered when re-visiting a buffer.

Maybe check out the rest of your init.vim / init.lua for autocmds that might affect folding?

Many people have many different workflows. They often have ideas about what a plugin must do to support their workflows. Then, they change workflows and now it becomes the most important thing that the plugin supports those. My impression is that this has become a source of premature "optimizations" in Telekasten, trying to support even the weirdest setups that don't make sense and are sometimes pure mental exercises by people who try to envision their perfect way of working. A few well-intentioned PRs later, we have side-effects introduced by authors who are unfamiliar with the codebase and couldn't imagine their local changes might affect other parts of the plugin. This worries me a bit.

I cannot support everyone's ever changing workflows. Telekasten is not my life. It's not a product. It was an itch that I scratched that seemed useful for others, too. I never got around implementing some advanced features that I wanted to see because I didn't have a need for them. For quite a while, I've been happy with how Telekasten works for me and that other people took care of developing it further for their specific use cases. I have so many projects to work on, Telekasten is "fine" for me. 

So, this is just the reality of many open source projects.

Ok, I got on a tangent there.

I doubt that Telekasten has gotten folding features recently, so there's nothing to disable. But, since there's the ftplugin stuff, try commenting that out as a test and see if it makes a difference in your multi markdown plugin setup.

**Comment by mediapathic** [comment]
@renerocksai I see from your response that I came off far, far more demanding than I intended, and for that I apologize. I absolutely agree that Telekasten is more than good enough (it is, in fact, the primary way I engage with my work in nvim. I certainly didn't mean to imply that you needed to significantly change anything just for my benefit. 

The knowledge that it doesn't (probably) touch folding and that it doesn't refresh a buffer when touching it is enough to know that I was wrong about my analysis here. You can consider this closed. 

Once again, I apologize.

**Comment by lambtho12** [comment]
@renerocksai, agree with you. The folding features implemented in ftplugin are not triggered by telekasten, so something else is probably doing it automatically. I agree with your "rant", even if it comes a bit out of the blue here :smile:
I am finally approaching the last months of my thesis. I think that before continuing with the refactoring, I will completely remove the `telekasten` filetype stuff as it seems to be a major pain in the a** while bringing few benefits (if any).

@mediapathic , did you find the issue? When you do, could you please update how you fixed it here so anyone having the same problem can see how to fix it.

**Comment by mediapathic** [comment]
@lambtho12 I eventually did find the issue, but it was to do with other plugins and settings too specific to be of help to anyone else looking here. The issue was that I was not thorough enough with my testing, and, for anyone searching for this problem here in the future, the answer is, to paraphrase rene, "telekasten is not causing your problem, look elsewhere" :)
