### ISSUE TITLE
Support for subfolders insert new note

### ISSUE THREAD

**Issue by daniel-vera-g** [renerocksai/telekasten.nvim#38]
I'm using telekasten as wiki with subfolders to organize topics a bit. 

When I'm in a file of a subfolder, say `home/subfolder/file.md` and try to create a new link through ~~`insert_link()`~~ `new_note()` it creates it in the root `home`.

Maybe one could do a setting like in Obsidian:

![image](https://user-images.githubusercontent.com/28257108/145728711-9e7003e2-cbcb-41b1-afb3-de13945e283b.png)

I think you addressed this a bit in https://github.com/renerocksai/telekasten.nvim/issues/12#issuecomment-982792303 .

Currently I'm using [`wiki.vim`](https://github.com/lervag/wiki.vim/blob/master/doc/wiki.txt#L1193) to create new notes in subfolders. Following a link there also creates it in the current directory like Obsidian/Foam/... 

Anyway, great Plugin and refreshing approach with Telescope 👍

**Comment by renerocksai** [comment]
I see a point there. I consider adding an option for that. I, for myself, do not want to worry what path my current note is in when I create a new one. I like to know that it's always created in the home dir unless I specify a different folder. 

So one man's feature sometimes is another one's bug :smile: - let there be options!

**Comment by daniel-vera-g** [comment]
> I see a point there. I consider adding an option for that. I, for myself, do not want to worry what path my current note is in when I create a new one. I like to know that it's always created in the home dir unless I specify a different folder.
> 
> So one man's feature sometimes is another one's bug 😄 - let there be options!

Thanks for the fast answer. The options feature would be great.  
When using Telekasten as Journal or with the Zettelkasten method I totally understand the current approach. But when using a Wiki I think it would help to be able to support subfolders.

Regarding:
> I like to know that it's always created in the home dir unless I specify a different folder.

Is it currently possible to specify a different folder? Couldn't find anything 🤔 

P.S: In the original description I meant `new_note()` and not `insert_link()` . But I think you got it the point.

**Comment by renerocksai** [comment]
> Thanks for the fast answer. The options feature would be great. When using Telekasten as Journal or with the Zettelkasten method I totally understand the current approach. 

> But when using a Wiki I think it would help to be able to support subfolders.

Can you elaborate on how sub-folders are not supported by this plugin? Notes are found in sub-folders even when you don't specify them in the `[[link]]`. They are considered when they are present in a `[[subfolder/link]]`. The `[[subfolder/link]]` is the current standard format of how links to notes in sub-folders are created. With a future option, that could be changed to never put sub-folders into links.

> Regarding:
> 
> > I like to know that it's always created in the home dir unless I specify a different folder.
> 
> Is it currently possible to specify a different folder? Couldn't find anything 

Yes. When prompted for a title, type in the subfolder(s) followed by a slash before you type in the title:

![image](https://user-images.githubusercontent.com/30892199/145779575-607cbfbc-3af2-469a-a4ee-e0210020369a.png)

**Comment by daniel-vera-g** [comment]
Thanks for the explanation, I think I understood your points.  Following this maybe the following could be feasible:

**Regarding just creating notes:** Typing the path when creating a note like you described works 👍  . So yeah, I think this could be leaved as it is.

**Directly typing non-existent link and creating the file:** This use case would be like the current `follow_link()` feature combined with creating notes on the fly:

1. Be in a file
2. Create a link `[[link]]`  or   `[[other/folder/link]]`. 
3. Then, being on the link(Like with `follow_link()`), using `new_note()` or `new_templated_note()` would create the note in the current(Single filename in Wikilink) directory or in a specific Path(Path in Wikilink). It would be cool if `follow_link()` creates the note if it does not exist.

That would help in keeping the flow of creating and following a link. Currently you've to more or less create a new File and then navigate back and insert the link. That's not suuuch a big deal, but typing the link and creating the note directly would be smoother. I think that's how most alternatives work, or do I oversee something?

---

So yeah, the current approach works. But Maybe you could take something out of my second thoughts. Nevertheless, for being a few weeks old it's pretty useful 😄

**Comment by renerocksai** [comment]
I appreciate that you took the time to write all this. But did you read the README?

From the highlights:
![image](https://user-images.githubusercontent.com/30892199/145838435-251fa140-8a23-48e1-918b-cb80b0c3403e.png)

From the section about the lua functions:
![image](https://user-images.githubusercontent.com/30892199/145838643-1ae17819-773d-4ecd-9914-5d4e48319a37.png)

So, what I will keep from your suggestions is an option that will make the plugin create new notes in the sub-directory of the currently active note in the editor. That spares you from having to type the folder name. However, what if you are in `sub/dir/one` and create `[[blog/cool new post]]` or some other weird case? 

That requires some conflict resolution protocol, with the following being the easiest (imho): 'when subfolders are present in a link to a non-existing note - and such a link is followed, ignore the current working directory and use the one specified in the link instead'. (Again, I am against relative links, shortest path links, as they are a recipe for broken links). I like 'the easiest', simple rules, because anything more complex often leads to confusion, misunderstandings, wrong expectations, and eventually to disappointment. Funnily enough, simple rules that are easy to understand are often also easy to work around should they get in your way. But that's a whole bunch of opinions :smile:.

Do you have other suggestions for how that scenario should be handled?

**Comment by daniel-vera-g** [comment]
> I appreciate that you took the time to write all this. But did you read the README?

Hmm, I read it but somehow oversaw it or so. I'm sorry.

> will make the plugin create new notes in the sub-directory of the currently active note in the editor

Yep, that would be great 👍 
I assume, that by creating new notes you also mean the case when `follow_link()` creates a new note.

> 'when subfolders are present in a link to a non-existing note - and such a link is followed, ignore the current working directory and use the one specified in the link instead'.

That's fine for me. I also get your point with relative links as we do not alter the link path on location change.

**Comment by renerocksai** [comment]
Yes, `follow_link()` / any method to create a new note would honor the new setting. That's the only consistent and sane option :smile:

Great! Will probably implement it soon! There's that day job though :smile: .

**Comment by renerocksai** [comment]
will update readme with new config options `new_note_location` and `template_handling` soon.
