### ISSUE TITLE
Insert file name in Wikilink on `insert_link`

### ISSUE THREAD

**Issue by daniel-vera-g** [renerocksai/telekasten.nvim#39]
This Issue is slightly related: to https://github.com/renerocksai/telekasten.nvim/issues/38#issue-1077904618 The general infos there also apply to this issue.

When inserting a new note with `insert_link()`,  I currently get a full path. For example(On MacOS):

> `[[/Users/USER/HOME/path/to/file/]]`

That works, but in general absolute paths are not that great. For example when switching machines or using the Wiki on different machines.

Also here, I took Inspiration from Obsidian. I personally use only the Filename in the Wikilinks. For example `[[Filename]]`. That means no path, no matter which subdirectory the file is in. This also currently works with the search features of Telekasten and is (I think) default in Obsidian and Foam I've used before.  
Nevertheless an option like in Obsidian would be helpful for people that need relative/full paths:

![image](https://user-images.githubusercontent.com/28257108/145729485-ecd1957d-c456-4fbc-b10b-036d7e5d36d7.png)

I've not testet it on Linux, but I don't think it should be related to MacOS. Also probably a bit related to #12

**Comment by renerocksai** [comment]
Please check your configuration and if you're running an up-to-date version of the plugin.

Maybe it's a trailing `/` in your configured `home` in your call to `setup()`.

Links to notes in subfolders were implemented to show the relative path to the `home` directory. If you don't specify a subdir in a link, the note in any subdir will still be found.

A config option that toggles between `[[title only]]` and `[[sub/dir/title]]` on `insert_link()` would make sense though. I don't see 'shortest path' as a good option since it is error-prone. Copying such a link to a different note wouldn't work anymore, for example.

**Comment by renerocksai** [comment]
Please re-open if you have further issues.

Did you figure out if you had a trailing slash or something in your `home` config?

Anyways, the new option `subdirs_in_links=false` will strip off any subdir components.

**Comment by daniel-vera-g** [comment]
> Did you figure out if you had a trailing slash or something in your `home` config?

Not really. It has a `-` in the folder name. But this shouldn't be the issue.
I am actually using the same config as in the README with a different home folder name. I also tested it on linux with the same behaviour. But if only I'm having the issue, it's probably something with my setup.
 
> Anyways, the new option `subdirs_in_links=false` will strip off any subdir components.

Thanks, that was fast!  It works as expected 👍

**Comment by renerocksai** [comment]
In preparation for #38, I just pushed some refactoring work. While doing it, I saw that filenames and paths containing any of the following: `( ) . % + - * ? [ ^ $` can cause funny problems if they're not escaped. I had not thought of escaping special regex-like characters, assuming most of them wouldn't be legal filename characters anyway. What a bug!!!

In your case, if I take the full path to a note and `gsub()`stitute the `home` directory by an empty string to remove it, the `home` will not get removed (because it will not be found) if it contains any of the special characters.

This would lead to full paths being returned.
