### ISSUE TITLE
Weekly note failed when week overlaps two years

### ISSUE THREAD

**Issue by Rom1deTroyes** [renerocksai/telekasten.nvim#53]
Yesterday was last year, and today is a new year, but we are in the same week : a classic problem to handle :thinking: 

Since the beginning of the week, `goto thisweek` opens the `2021-W52` file, but today (first January 2022), it goes to `2022-W52` which stands for week including 12/26/2022 to 01/01/2023 (52nd week of year 2022).

Note that only the «week year number» part is affected : the daily recap of the week have good dates.

![image](https://user-images.githubusercontent.com/8625432/147857343-d1f22d43-4f9a-4e29-b22b-3b5399d376e5.png)

The workaround is simple : just wait tomorrow to copy/paste the content, next year, the overlapping is just one day and for 2024 there is no overlap, so the urgency is very low, but, hey, don't we aim perfection ? :1st_place_medal: 

Thanx for this great tool, coming from a markdown vimwiki + custom daily note system, the transition is painless and my power-user level goes +100 :+1:

**Comment by renerocksai** [comment]
You can hardly imagine how much effort went into getting the date stuff right. There were 2 oversights, though: `goto_thisweek()` didn't make use of those efforts, and the simple check for W52 in January failed to the week being returned as string instead of an integer :facepalm: .

However, all other stuff, like working out what date is the `{{monday}}` of week 52 in 2021 - also, when encountered in a link, works, adhering to iso-8601.

The `goto_week()` case has been fixed now. It will be invalid for years where the Thursday falls into the new year - but we have > 4 years to fix that by making use of the new iso-conforming date stuff.

Thanks for pointing it out! Happy new year! :partying_face:
