### ISSUE TITLE
Links inside square brackets are not underlined

### ISSUE THREAD

**Issue by tuborgman** [renerocksai/telekasten.nvim#54]
Hi!

Absolutely amazing plugin. What I am missing in my neovim setup is the underlined links for [[LinkToNote]]. Though, in the readme it said that it should be underlined.

using NeoVIM v0.7.0-dev and gruvbox theme (morhetz/gruvbox).

Thanks

**Comment by Rom1deTroyes** [comment]
Strangely, I got the highlighting when I insert the link using NeoSolarized dark :
![image](https://user-images.githubusercontent.com/8625432/147858782-c2bc3278-45d0-4d00-b4ef-b0fc8d5fa780.png)

But if I change the `colorsheme`, it disappear, even if I change it back to NeoSolarized :
![image](https://user-images.githubusercontent.com/8625432/147858705-f6c4eb04-ec4a-4fb5-985b-d961969fc6ff.png) ![image](https://user-images.githubusercontent.com/8625432/147858821-2ba7050a-6013-4393-ac55-d73c3b255444.png)

Opening back Neovim restore the highlights.

**Comment by tuborgman** [comment]
Doesn't work for me even in NeoSolarized...

**Comment by renerocksai** [comment]
I observe this when changing colorscheme at runtime. If I change the colorscheme in my `init.vim`, it works. 

The reason is: colorschemes know nothing about telekasten. Hence, they don't define highlights (colors, styles like bold, underline) for telekasten-specific syntax. So when you change colorscheme, all highlights are cleared before the new ones are applied. But since your colorschemes don't know anything about `tklink` etc, they will not set highlights for them. When you switch back to your original colorscheme, the highligts for the telekasten syntax still remain cleared, hence you don't get them back.

Since we cannot expect all colorschemes to support our plugin, we need a workaround.

You could:
- put all the `hi tklink ...` and related commands in a separate file and reload it (`:source myhighlights.vim`) on
  demand. You could define a mapping for that to have it handy.
- just change colorscheme in your `init.vim` instead of on-the-fly
- define a vim or lua function that sets all the highlights and call it, optionally via mapped key combination, after you've changed colorscheme

Mind you, if you change color scheme, you probably also want to change the colors of the telekasten-specific syntax. 

One way to get colorscheme-matching highlights for links would be to `hi link tklink markdownLinkText` and `hi link
tkBrackets markdownLinkDelimiter`. For  `tkHighlight` there is no markdown equivalent, so you have to set it to some
value that makes sense for the desired colorscheme.

**Comment by renerocksai** [comment]
> Doesn't work for me even in NeoSolarized...

You are not specific. Have you put the highlight commands in your `init.vim`? Check the README.
