### ISSUE TITLE
Better handle cases where a file/directory is not present where it is expected

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#63]
As discussed somewhere else (https://github.com/renerocksai/telekasten.nvim/pull/44#issuecomment-994482567), I have my journal notes in an encrypted directory that I need to mount before accessing it. _Obviously_, I forget to mount it 50% of the time. In that case, Telekasten just throws a handful of errors when I want to create a daily note.

We should add a test before to look if the directory exists or not. If not, then ask the user if it should be created or if the operation should be cancelled altogether.

I have not tested other cases, but I suppose similar errors may be possible if the template folders are not where they are expected.

**Comment by renerocksai** [comment]
:joy: lol, I feel you! Yeah, that's a case I did not anticipate.

I use `git-crypt` to encrypt my entire notes folder and also have it encrypted transparently. Git-crypt allows for encrypting specific files, folders, as one specifies in `.gitattributes`. I can link you to a blog post(s) which describes everything in far too much detail :smile: if you're interested. Because it needs a helper script for merging, e.g.

Anyway, I should put in a test or two. There are existing checks where telekasten fails gracefully, e.g. if a template file doesn't exist.

Asking whether a directory should be created can lead to its own set of problems. Dir creation can fail. So in any case, more tests are probably necessary. It is assumed that the `home` dir exists.

**Comment by renerocksai** [comment]
The plugin will now check for all configured dirs (not `nil`) on startup and ask for creation if they don't exist. If creation fails, a real error with stack-trace is shown, thanks to plenary's Path module.

I hope this covers your case well enough. Asking for dir creation will make you not miss the error :smile:.

**Comment by lambtho12** [comment]
Sorry to bother you again, but I am not quite happy with this solution actually :sweat_smile: 

Checking this at startup require me to have my folders mounted **everytime I need to use nvim**. So whenever I want to work on some code or whatnot, it will bother me and ask me to create the folders first. Which has nothing to do with what I am currently doing.

I think the best case would be to test only when the files need to be accessed (opened, saved, or a picker for files in these directory is used). A middle ground alternative would be to do these checks only if the buffer is of ft=zettelkasten, so at least I will only be bothered when I plan to work on my notes.

----
Besides that, the prompt is rather vague. When I open neovim, I just get promped: ``Shall I create it? [y/N]`. It should tell me:
1. that the question comes from telekasten
2. what the "it" is...

**Comment by renerocksai** [comment]
![image](https://user-images.githubusercontent.com/30892199/149660357-a33b3263-e4a2-46fe-9a94-6e7a9e57d376.png)

Hi, see above. This is how it looks in my nvim. Your config seems to limit messages to 1 line.

Always checking dirs ... OK, it's doable...

**Comment by lambtho12** [comment]
> Hi, see above. This is how it looks in my nvim. Your config seems to limit messages to 1 line.

Oh yeah, I did not think of that.. :D I will have a look at my nvim config then :D

**Comment by renerocksai** [comment]
I'm throwing it all in 1 line now. Only drawback: a single line plus asking for input seems not possible as error. Or wait....I'll try sth.

**Comment by lambtho12** [comment]
Yep, it was my config. I had `opt("o", "cmdheight", 2)` no matter the value I give it, it only display the last line of the message for some reason. So I just got rid of it. The error displays as expected now. No need to try it in a one liner just for me :D

**Comment by renerocksai** [comment]
A user input prompt will not go into the `:messages` buffer - but I think that's liveable.

**Comment by renerocksai** [comment]
It's a one-liner now :smile: - who knows what other people have in their configs :smile:. Thanks for checking it so quickly!!!

**Comment by renerocksai** [comment]
OK, it's now not done on setup() but on (first) use.

**Comment by lambtho12** [comment]
Awesome!

**Comment by lambtho12** [comment]
I just had a look at the implementation, it seems you opted to check if all directories are properly setup in all functions. Why not only check if the relevant ones are setup for each function? Of course, I understand the logic for the `home` directory, but for the rest, I am not so sure... 

For instance, `find_notes` does not need to look for images or daily, so it should not matter if these are mounted or not, no? Likewise, `find_daily_note` should not care about images or templates, etc... Why not having a `home_dir_check()` and then replace `global_dir_check()` by `home_dir_check() and check_dir_and_ask(M.Cfg.image_subdir, "image_subdir")` for instance in the case of `imgFromClipboard`?


I am maybe missing something here and maybe this is only the case for my specific case with very separated directories. I should definitely try to find some time to look at git-crypt and stop being bothered by all that :smile:

**Comment by renerocksai** [comment]
Therer are reasons:

- cost-benefit analysis
- lack of understanding of your particular use-case
- trying to avoid side-effects

For instance, `follow_link` needs to check for daily and weekly, too. If it only checked for home, this could have unintended consequences. Especially in configurations where the other dirs are not part of the home dir, it's easy to forget to check for a specific dir when at first it appears it has nothing to do with the task at hand. 

When in `setup()` you tell the plugin what your dirs are, it is only fair that it checks for these directories.

My intention was to postpone the check until the first use of the plugin - which made sense in terms of your middle ground suggestion.

On to cost-benefit. I have so many things that I want to do that take this plugin further, apart from a demanding job. The seconds spared by doing it this way, achieving what I thought was a good compromise seemed to be worth it.

Closing remarks: Based on your latest remarks I was under the impression that you had only "your journal archive" in an encrypted directory that you need to mount before using telekasten. Re-reading your comments again, I see that you separate journal and other notes. So even the current approach might not work well for you. I hope you're not implying that you separately mount your image / media "sub" directory, too.

The `follow_link()` issue summarizes what I am getting at: any link is intended to be follow-able. By design, dailies and weeklies are not prefixed with their daily / weekly subdir names, as I consider that "ugly" when it's (in my eyes) clearly not necessary. In your case, it would be best to only check for daily when testing for note-presence there. I would argue this unnecessarily complicates everything. When you add to that the optional note-creation problem where we also differentiate by daily-looking, weekly-looking, and "normal" links it gets even worse. Making sure every check is only done when it's absolutely necessary would have meant going through the code very thoroughly. 

I would also argue that in some ways, late checking counters the principle of least surprise. When you use telekasten for an hour you don't expect it to suddenly pop up a message that some dir is missing. It's no strong support for that argument but I hope you get my point of view. I would prefer that the plugin didn't check at all (no handholding) - and if I make an error things would break, ideally with a good hint about what went wrong. So I prefer to have checks run when I first use the plugin - all checks and not one now, another one later.

Git-crypt won't solve your general issue: if you 'lock' your archive - everything will be garbled. At least, directories won't be missing and you'd be able to write new notes. However, it is git-based, so until you check things into git (vim-fugitive!!!), they won't be encrypted. I leave my checked-out archive un-locked at all times. So it's only encrypted server-side. I trust my computer enough - I am the only user anyway. If I feel paranoid, e.g. before traveling with a laptop, I can always lock the archive - which will encrypt it locally. 

So, because your directories won't disappear, the git-crypt route might be an improvement for you. But if you use separate archives / repositories for notes and journals and maybe even images, you will still have to conditionally unlock them - and make sure you lock them when you're done. 

Some relief might come by adjusting your key-bindings. You can prefix your telekasten shortcuts by `!mount /this` - possibly. If consecutive commands are impossible, then you'd be able to wrap setup and tear-down into little helper-functions... Maybe that improves things.

**Comment by Rom1deTroyes** [comment]
This can be of interest for this use-case ?

https://gist.github.com/ptrv/2387956

 Using gpg encrypted files and set the file type to telekasten may be a strong way to keep things secure (I don't have made any test this way, but sometimes open gpg files with this in my init.vim :-)
