### ISSUE TITLE
[BUG] The offer to create the `img/` directory uses relative path

### ISSUE THREAD

**Issue by zalegrala** [renerocksai/telekasten.nvim#69]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
It looks to me like the `img/` directory gets created from where vim was launched, not the notes path.

**To Reproduce**
1. Start nvim outside of the notes directory
2. say yes to create the `img` directory.
3. note that the new directory is outside of the notes path.

**Expected behavior**
The directory should get created at the base of the notes structure, not the cwd of where vim was launched.

**Operating system (please complete the following information):**
 - OS: Linux

**Comment by jglueckstein** [comment]
I can confirm this behavior.

**Comment by lambtho12** [comment]
Indeed, this is because the other directories (templates, weekly and dailies) are specified as absolute path in the config, while for images it should be a subdirectory.

So the check function that creates the directory should work a bit differently for images.
https://github.com/renerocksai/telekasten.nvim/blob/f20fb7862b35be4795ad76ed08d1011f94f59d0b/lua/telekasten.lua#L162-L172


An other way around would be to have the images directories as a full path as well in the config (but then the image search functions should be modified I guess)

**Comment by zalegrala** [comment]
Thanks for the response.  I've updated my config to include the absolute path to the image_subdir.

**Comment by lambtho12** [comment]
@zalegrala I do not think this should be considered closed. Using an absolute path in the config for `image_subdir` is definitely going to cause issues when you will try to paste image from the clipboard. I do not know the best approach to solve this properly, so you may want to keep it open while we wait for @renerocksai 's input.

**Comment by renerocksai** [comment]
Sorryyyyy! That's my bad when I introduced the dir check yesterday. Will fix ASAP.

Please do not put absolute paths into your configs for `image_subdir`!

**Comment by renerocksai** [comment]
This should fix it.
