### ISSUE TITLE
[BUG] Following links doesn't appear to work if the link to be followed is a checklist item

### ISSUE THREAD

**Issue by zalegrala** [renerocksai/telekasten.nvim#91]
**Please confirm**
- [ x] I am running the latest version of this plugin

**Describe the bug**
When I have a checklist which include a link, the link doesn't follow.

**To Reproduce**

For example.

```
- [ ] Do a thing on ticket [123](https://github.com)
```

Then put the cursor on `123` and use the `follow_link` command.

**Expected behavior**
The link is followed when the issue is on a todo item.

**Operating system (please complete the following information):**
 - OS: Linux

**Comment by lambtho12** [comment]
I am currently investigating this. 
It seems that the issue is in `taglinks/taglinks.lua` with the `is_tag_or_link_at`function. If the url link is in a todo list, this function returns `link`(_i.e._ a zettel link) while it should return `nil`. I do not know yet how to solve this, but that should not be that complicated...

Although, when testing, the urls never open on my machine (even if they are not in a to-do list). Is it also the case for you?
Could anyone try the following:
```markdown
Lorem ipsum [first link](www.github.com).
- What about a [link in a list](www.github.com)
```
and tell me if using `follow_link` on the urls work?

**Comment by lambtho12** [comment]
> Although, when testing, the urls never open on my machine (even if they are not in a to-do list). Is it also the case for you? Could anyone try the following:
> 
> ```gfm
> Lorem ipsum [first link](www.github.com).
> - What about a [link in a list](www.github.com)
> ```
> 
> and tell me if using `follow_link` on the urls work?

Ok my bad, seems that this is because the link should start with `https://`. So I will just focus on the original issue...
